version: '3.5'

services:
  pg_post:
    image: postgres
    container_name: pg_post_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-post_service}
      PGDATA: ${PGDATA:-/data/postgres}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pg_post:${PGDATA:-/data/postgres}
    networks:
      - pg_post

volumes:
  pg_post:

networks:
  pg_post:
